check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.35.1
  build-stratergy: Source
  registry: "quay.io"
  registry-org: "thoth-station"
  registry-project: "package-releases-job"
  registry-secret: "thoth-station-thoth-pusher-secret"
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "package-releases-job"
  overlay-contextpath: "package-releases/overlays/test/imagestreamtag.yaml"
