apiVersion: v1
kind: Template
metadata:
  name: package-releases-imagestream
  annotations:
    description: This is Thoth Core - Package Releases ImageStream
    openshift.io/display-name: "Thoth: Package Releases ImageStream"
    version: 0.2.0
    tags: poc,thoth,ai-stacks,package-releases
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Package Releases
      ImageStream as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: package-releases-imagestream
    app: thoth
    component: package-releases

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      labels:
        app: thoth
        component: package-releases
      name: package-releases-job
    spec:
      name: latest
      lookupPolicy:
        local: true
